name: Tests

on: [push, pull_request]

env:
  PY_COLOR: 1
  COLUMNS: 120
  TESSDATA_PREFIX: /usr/local/share/tessdata
  DISPLAY: ':99.0'

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tesseract-ocr
        run: |
          sudo add-apt-repository ppa:alex-p/tesseract-ocr-devel
          sudo apt-get update
          sudo apt-get install tesseract-ocr
          sudo wget https://github.com/tesseract-ocr/tessdata/raw/main/eng.traineddata -P $TESSDATA_PREFIX
          sudo wget https://github.com/arturaugusto/display_ocr/raw/master/letsgodigital/letsgodigital.traineddata -P $TESSDATA_PREFIX
      - name: Install ssocr
        run: |
          sudo apt-get install libimlib2 libimlib2-dev
          git clone --branch v2.22.1 --single-branch https://github.com/auerswal/ssocr.git
          cd ssocr/
          make
          sudo make install
      - name: Install and configure graphics (for Qt)
        run: |
          sudo apt-get install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils libgl1-mesa-dev
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
      - name: Install Python dependencies and package
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python -m pip install --upgrade --editable .[tests]
      - name: Verify tesseract-ocr installation
        run: |
          tesseract --version
          tesseract --list-langs
      - name: Verify ssocr installation
        run: ssocr --version || true
      - name: Run tests
        run: python -m pytest
